-- FoodShare Supabase Database Schema

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Restaurants Table
CREATE TABLE public.restaurants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    location_code VARCHAR(50) NOT NULL,
    address TEXT,
    contact_phone VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. NGOs Table
CREATE TABLE public.ngos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    location_code VARCHAR(50) NOT NULL,
    address TEXT,
    contact_phone VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Donations Table
-- Normal Donors might not have an associated restaurant_id (it will be NULL)
CREATE TABLE public.donations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    restaurant_id UUID REFERENCES public.restaurants(id) ON DELETE SET NULL,
    donor_name VARCHAR(255), -- For normal donors without an account
    food_type VARCHAR(100) NOT NULL,
    quantity_kg NUMERIC(10, 2) NOT NULL,
    expiry_hours INT NOT NULL,
    location_code VARCHAR(50) NOT NULL,
    image_url TEXT,
    status VARCHAR(50) DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'ASSIGNED', 'COLLECTED', 'EXPIRED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Requests Table (Made by NGOs)
CREATE TABLE public.requests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ngo_id UUID REFERENCES public.ngos(id) ON DELETE CASCADE,
    food_category VARCHAR(100),
    urgency INT NOT NULL CHECK (urgency IN (1, 2, 3)), -- 1: Normal, 2: High, 3: Critical
    needed_kg NUMERIC(10, 2),
    status VARCHAR(50) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'MATCHED', 'FULFILLED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Matches Table (Generated by C Engine, pushed by Python)
CREATE TABLE public.matches (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    donation_id UUID REFERENCES public.donations(id) ON DELETE CASCADE,
    request_id UUID REFERENCES public.requests(id) ON DELETE CASCADE,
    ngo_id UUID REFERENCES public.ngos(id) ON DELETE CASCADE,
    match_score INT NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING_COLLECTION' CHECK (status IN ('PENDING_COLLECTION', 'COLLECTED', 'CANCELLED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Row Level Security (RLS) Setup (Basic policies for a starting point)

ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ngos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- Allow public read for testing, restrict insert/update in production
CREATE POLICY "Public Read All" ON public.restaurants FOR SELECT USING (true);
CREATE POLICY "Public Read All NGOs" ON public.ngos FOR SELECT USING (true);
CREATE POLICY "Public Read Donations" ON public.donations FOR SELECT USING (true);
CREATE POLICY "Public Insert Donations" ON public.donations FOR INSERT WITH CHECK (true); -- Allow normal donors to post
CREATE POLICY "Public Read Requests" ON public.requests FOR SELECT USING (true);
CREATE POLICY "Public Read Matches" ON public.matches FOR SELECT USING (true);

-- Functions and Triggers (Optional: Update donation status on match)
